require:
  - rubocop-rspec
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Rake/Desc:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
